import type { Employee } from './types';

export const createTestEmployee = (overrides: Partial<Employee> = {}): Employee => ({
  id: 'test-employee@example.com',
  entityId: 'TEST-ENTITY',
  name: 'Test Employee',
  email: 'test-employee@example.com',
  designation: 'Software Engineer',
  department: 'Engineering',
  status: 'Active',
  bankName: 'Maybank',
  accountNo: '0000000000',
  basicSalary: 5000,
  housingAllowance: 0,
  transportAllowance: 0,
  overtime: 0,
  performanceBonus: 0,
  epfRateEmployee: 11,
  epfRateEmployer: 13,
  socsoEmployee: 0,
  socsoEmployer: 0,
  eisEmployee: 0,
  eisEmployer: 0,
  taxPcb: 0,
  unpaidLeave: 0,
  hrdCorp: 0,
  nricPassport: '',
  nationality: 'Malaysian',
  taxNumber: '',
  employmentType: 'Permanent',
  maritalStatus: 'Single',
  eligibleForStatutory: 'Yes',
  optInEpf: true,
  optInSocso: true,
  optInEis: true,
  optInPcb: true,
  emergencyContactName: '',
  emergencyContactRelation: '',
  emergencyContactPhone: '',
  dateOfJoined: '2020-01-01',
  ...overrides
});
